import webvtt
from nltk.corpus import stopwords
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
from PIL import Image

transcript_file = "./Transcripts/Meeting in _Wk 15 - Feature Engineering_ _AutoGeneratedCaption.vtt"
vtt = webvtt.read(transcript_file)

lines = []
for l in vtt:
    lines.extend(l.text.strip().splitlines())

output = " ".join(lines).replace(',',' ').lower()

output_file = 'wordcloud.jpg'
sw = list(STOPWORDS)+list(stopwords.words('english'))+['uh','um','uhm','kind','of']
wc = WordCloud(stopwords=sw).generate(output)
#wordcloud = wc.generate_from_text(output)
wc.to_file(output_file)
image = Image.open(output_file)
image.show()




